services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexantara_api
    ports:
      - "${PORT}:9000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY}
      PORT: ${PORT}
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_nexantara_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - nexantara-api_postgres_data:/var/lib/postgresql/data

volumes:
  nexantara-api_postgres_data:
    external: true
